export const SALONS_CREATE_MODAL_TOGGLE = 'SALONS_CREATE_MODAL_TOGGLE';
export const SALONS_SELECT_MODAL_TOGGLE = 'SALONS_SELECT_MODAL_TOGGLE';
export const SALONS_LIST_LOADING = 'SALONS_LIST_LOADING';
export const SALONS_ITEM_LOADING = 'SALONS_ITEM_LOADING';
export const SALONS_ITEM_SELECT = 'SALONS_ITEM_SELECT';
export const SALONS_FETCH_LIST = 'SALONS_FETCH_LIST';
export const SALONS_FETCH_ITEM = 'SALONS_FETCH_ITEM';
